# require 'rails_helper'
#
# # This spec was generated by rspec-rails when you ran the scaffold generator.
# # It demonstrates how one might use RSpec to test the controller code that
# # was generated by Rails when you ran the scaffold generator.
# #
# # It assumes that the implementation code is generated by the rails scaffold
# # generator. If you are using any extension libraries to generate different
# # controller code, this generated spec may or may not pass.
# #
# # It only uses APIs available in rails and/or rspec-rails. There are a number
# # of tools you can use to make these specs even more expressive, but we're
# # sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# RSpec.describe "/vacancies", type: :request do
#   # Vacancy. As you add validations to Vacancy, be sure to
#   # adjust the attributes here as well.
#   let(:valid_attributes) do
#     skip("Add a hash of attributes valid for your model")
#   end
#
#   let(:invalid_attributes) do
#     skip("Add a hash of attributes invalid for your model")
#   end
#
#   describe "GET /index" do
#     it "renders a successful response" do
#       Vacancy.create! valid_attributes
#       get vacancies_url
#       expect(response).to be_successful
#     end
#   end
#
#   describe "GET /show" do
#     it "renders a successful response" do
#       vacancy = Vacancy.create! valid_attributes
#       get vacancy_url(vacancy)
#       expect(response).to be_successful
#     end
#   end
#
#   describe "GET /new" do
#     it "renders a successful response" do
#       get new_vacancy_url
#       expect(response).to be_successful
#     end
#   end
#
#   describe "GET /edit" do
#     it "render a successful response" do
#       vacancy = Vacancy.create! valid_attributes
#       get edit_vacancy_url(vacancy)
#       expect(response).to be_successful
#     end
#   end
#
#   describe "POST /create" do
#     context "with valid parameters" do
#       it "creates a new Vacancy" do
#         expect do
#           post vacancies_url, params: { vacancy: valid_attributes }
#         end.to change(Vacancy, :count).by(1)
#       end
#
#       it "redirects to the created vacancy" do
#         post vacancies_url, params: { vacancy: valid_attributes }
#         expect(response).to redirect_to(vacancy_url(Vacancy.last))
#       end
#     end
#
#     context "with invalid parameters" do
#       it "does not create a new Vacancy" do
#         expect do
#           post vacancies_url, params: { vacancy: invalid_attributes }
#         end.to change(Vacancy, :count).by(0)
#       end
#
#       it "renders a successful response (i.e. to display the 'new' template)" do
#         post vacancies_url, params: { vacancy: invalid_attributes }
#         expect(response).to be_successful
#       end
#     end
#   end
#
#   describe "PATCH /update" do
#     context "with valid parameters" do
#       let(:new_attributes) do
#         skip("Add a hash of attributes valid for your model")
#       end
#
#       it "updates the requested vacancy" do
#         vacancy = Vacancy.create! valid_attributes
#         patch vacancy_url(vacancy), params: { vacancy: new_attributes }
#         vacancy.reload
#         skip("Add assertions for updated state")
#       end
#
#       it "redirects to the vacancy" do
#         vacancy = Vacancy.create! valid_attributes
#         patch vacancy_url(vacancy), params: { vacancy: new_attributes }
#         vacancy.reload
#         expect(response).to redirect_to(vacancy_url(vacancy))
#       end
#     end
#
#     context "with invalid parameters" do
#       it "renders a successful response (i.e. to display the 'edit' template)" do
#         vacancy = Vacancy.create! valid_attributes
#         patch vacancy_url(vacancy), params: { vacancy: invalid_attributes }
#         expect(response).to be_successful
#       end
#     end
#   end
#
#   describe "DELETE /destroy" do
#     it "destroys the requested vacancy" do
#       vacancy = Vacancy.create! valid_attributes
#       expect do
#         delete vacancy_url(vacancy)
#       end.to change(Vacancy, :count).by(-1)
#     end
#
#     it "redirects to the vacancies list" do
#       vacancy = Vacancy.create! valid_attributes
#       delete vacancy_url(vacancy)
#       expect(response).to redirect_to(vacancies_url)
#     end
#   end
# end
